"""Initial Migration

Revision ID: 42533fabf9e3
Revises: 
Create Date: 2022-07-25 14:20:08.582801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42533fabf9e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorate_colour', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorate_colour')
    # ### end Alembic commands ###
